services:
  hello-eureka-peer-1:
    build: ./hello-eureka
    ports:
      - "8761:8761"
    environment:
      - server.port=8761
      - spring.application.name=hello-eureka
      - eureka.client.register-with-eureka=false
      - eureka.client.fetch-registry=false
      - eureka.client.service-url.defaultZone=http://hello-eureka-peer-2:8762/eureka
      - eureka.instance.hostname=hello-eureka-peer-1
      - TZ=Asia/Seoul

  hello-eureka-peer-2:
    build: ./hello-eureka
    ports:
      - "8762:8761"
    environment:
      - server.port=8761
      - spring.application.name=hello-eureka
      - eureka.client.register-with-eureka=false
      - eureka.client.fetch-registry=false
      - eureka.client.service-url.defaultZone=http://hello-eureka-peer-1:8761/eureka
      - eureka.instance.hostname=hello-eureka-peer-2
      - TZ=Asia/Seoul

  hello-gateway:
    build: ./hello-gateway
    deploy:
      replicas: 2
    ports:
      - "8080-8081:8080"
    environment:
      - eureka.client.service-url.defaultZone=http://hello-eureka-peer-1:8761/eureka, http://hello-eureka-peer-2:8762/eureka
      - TZ=Asia/Seoul
    depends_on:
      - hello-eureka-peer-1
      - hello-eureka-peer-2

  hello-api:
    build: ./hello-web
    deploy:
      replicas: 2
    ports:
      - "8900-9000:8081"
    environment:
      - eureka.client.service-url.defaultZone=http://hello-eureka-peer-1:8761/eureka, http://hello-eureka-peer-2:8762/eureka
      - TZ=Asia/Seoul
    depends_on:
      - hello-eureka-peer-1
      - hello-eureka-peer-2

  hello-api-2:
    build: ./hello-web
    deploy:
      replicas: 1
    ports:
      - "9001-9100:8081"
    environment:
      - eureka.client.service-url.defaultZone=http://hello-eureka-peer-1:8761/eureka, http://hello-eureka-peer-2:8762/eureka
      - TZ=Asia/Seoul
    depends_on:
      - hello-eureka-peer-1
      - hello-eureka-peer-2
