services:
  hello-eureka-peer-1:
    build: ./hello-eureka
    container_name: hello-eureka-peer-1
    ports:
      - "8761:8761"
    environment:
      - server.port=8761
      - spring.application.name=hello-eureka
      - eureka.client.register-with-eureka=true
      - eureka.client.fetch-registry=false
      - eureka.client.service-url.defaultZone=http://hello-eureka-peer-1:8761/eureka, http://hello-eureka-peer-2:8762/eureka
      - eureka.instance.hostname=hello-eureka-peer-1
      # 임대(lease)가 취소되는 시점을 결정할 때 사용된다. 레플리카인 경우 0으로 설정 필요 See InstanceRegistryProperties
      - eureka.instance.registry.default-open-for-traffic-count=0

  hello-eureka-peer-2:
    build: ./hello-eureka
    container_name: hello-eureka-peer-2
    ports:
      - "8762:8762"
    environment:
      - server.port=8762
      - spring.application.name=hello-eureka
      - eureka.client.register-with-eureka=true
      - eureka.client.fetch-registry=false
      - eureka.client.service-url.defaultZone=http://hello-eureka-peer-1:8761/eureka, http://hello-eureka-peer-2:8762/eureka
      - eureka.instance.hostname=hello-eureka-peer-2
      # 임대(lease)가 취소되는 시점을 결정할 때 사용된다. 레플리카인 경우 0으로 설정 필요 See InstanceRegistryProperties
      - eureka.instance.registry.default-open-for-traffic-count=0

  hello-gateway:
    build: ./hello-gateway
    deploy:
      replicas: 2
    ports:
      - "8080-8081:8080"
    environment:
      # fetching 타임을 줄여 런타임에 실시간으로 변경된 정보를 가져온다.
      - eureka.client.registry-fetch-interval-seconds=5
      - eureka.client.service-url.defaultZone=http://host.docker.internal:8761/eureka, http://host.docker.internal:8762/eureka
      # 유레카에서 변경되는 정보만 가져온다. See EurekaClientConfigBean 페치 사이클 변경에 쉽게 대응할 수 있다.
      - eureka.client.disable-delta=true
      - server.shutdown=graceful
    depends_on:
      - hello-eureka-peer-1
      - hello-eureka-peer-2
    extra_hosts:
      - host.docker.internal:host-gateway

  hello-api:
    build: ./hello-web
    deploy:
      replicas: 2
    ports:
      - "8900-9000:8081"
    environment:
      - eureka.client.service-url.defaultZone=http://host.docker.internal:8761/eureka, http://host.docker.internal:8762/eureka
      - eureka.instance.prefer-ip-address=true
      - server.shutdown=graceful
    depends_on:
      - hello-eureka-peer-1
      - hello-eureka-peer-2
    extra_hosts:
      - host.docker.internal:host-gateway

  hello-api-2:
    build: ./hello-web
    deploy:
      replicas: 1
    ports:
      - "9001-9100:8081"
    environment:
      - eureka.client.service-url.defaultZone=http://host.docker.internal:8761/eureka, http://host.docker.internal:8762/eureka
      - eureka.instance.prefer-ip-address=true
      - server.shutdown=graceful
    depends_on:
      - hello-eureka-peer-1
      - hello-eureka-peer-2
    extra_hosts:
      - host.docker.internal:host-gateway
