server:
  port: 8080

management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health
    jmx:
      exposure:
        include: info, health

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: hello-service
          uri: lb://API-HELLO
          predicates:
            - Path=/hello/**
          filters:
            - RewritePath=/hello/(?<path>.*),/$\{path}
