server:
  shutdown: graceful
  port: 8080

eureka:
  client:
    service-url:
      registry-fetch-interval-seconds: 5
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health
    jmx:
      exposure:
        include: info, health

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: hello-service
          uri: lb://API-HELLO
          predicates:
            - Path=/hello/**
          filters:
            - RewritePath=/hello/(?<path>.*),/$\{path}
