server:
  port: 8081
#  shutdown: graceful

management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health
    jmx:
      exposure:
        include: info, health

spring:
  application:
    name: api-hello
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
